language: go
sudo: true
go:
  - 1.6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libnl-3-dev libnl-genl-3-dev build-essential ipvsadm iptables
  - sudo ln -s $(which go) /usr/bin/go
before_script:
  - sudo modprobe ip_vs
script:
  - make ci
after_success:
  - bash <(curl -s https://codecov.io/bash)
