sudo: required

language: go

services:
  - docker

jobs:
  include:
    - stage: test
      script: docker-compose run ci
    - stage: test
      script: docker-compose run e2e

after_success:
  - bash <(curl -s https://codecov.io/bash)
