version: '2'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    privileged: true
    environment:
      STORE_ADDRESS: consul://172.100.0.30:8500
    volumes:
      - ".:/go/src/github.com/luizbafilho/fusis/"
      - "/lib/modules:/lib/modules"
    depends_on:
      - consul
    working_dir: /go/src/github.com/luizbafilho/fusis/
    command: sh -c "go build -o bin/fusis && bin/fusis balancer"
    networks:
      default:
        ipv4_address: 172.100.0.5

  test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    privileged: true
    environment:
      STORE_ADDRESS: consul://172.100.0.30:8500
    volumes:
      - ".:/go/src/github.com/luizbafilho/fusis/"
      - "/lib/modules:/lib/modules"
    depends_on:
      - consul
    # command: go test -race ./...
    command: go test github.com/luizbafilho/fusis/store

  fusis:
    build:
      context: .
    privileged: true
    depends_on:
      - consul
      - bird
    volumes:
      - "./fusis.toml:/etc/fusis.toml"
      - "/lib/modules:/lib/modules"
    networks:
      default:
        ipv4_address: 172.100.0.10

  bird:
    build:
      context: .
      dockerfile: Dockerfile.bird
    privileged: true
    volumes:
      - "./bird.conf:/etc/bird/bird.conf"
    networks:
      default:
        ipv4_address: 172.100.0.20

  consul:
    image: consul:0.7.1
    networks:
      default:
        ipv4_address: 172.100.0.30

  etcd:
    environment:
      ETCDCTL_API: 3
    image: quay.io/coreos/etcd:v3.2.7
    command:
       /usr/local/bin/etcd
        --name docker-compose
        --listen-client-urls http://0.0.0.0:2379
        --advertise-client-urls http://0.0.0.0:2379
        --listen-peer-urls http://0.0.0.0:2380
        --initial-advertise-peer-urls http://0.0.0.0:2380
        --initial-cluster docker-compose=http://0.0.0.0:2380
        --initial-cluster-token my-etcd-token
        --initial-cluster-state new
    networks:
      default:
        ipv4_address: 172.100.0.40

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.0.0/24

